language: php

php:
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer selfupdate
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh
  - vendor/symfony-cmf/testing/bin/server & PID=$!


script:
  - phpunit --coverage-clover=coverage.clover
  - phpcs --ignore=/vendor/*,/Tests/Resources/app/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

notifications:
  email: "nbastien@prestaconcept.net"
